### ISSUE TITLE
FSK tx not working with bitrate over 25592

### ISSUE THREAD

**Issue by mostorer** [dernasherbrezon/sx127x#18]
Setting a BitRate of 38.400 on the FSK TX example, I saw that the tx callback is never called, as the first packet send is not done.

I reverted back to 4.800 and all is working, so I tried gradually rising the BitRate.
The result I have found is that up to 25592 all is working as expected, but over that rate, the tx packet is not sent.

**Comment by dernasherbrezon** [comment]
I was able to reproduce the issue.

It looks like timing issue. If I put 1s delay between individual packets, then 38400 baud works fine. Maybe transceiver not fully stop on TxDone interrupt and cannot start new tx.

So I tried:

- tx with and without sequencer
- different frequency deviation
- different SPI clock

Wasn't able to pinpoint the problem. Will keep experimenting.

**Comment by dernasherbrezon** [comment]
The root cause was incorrect interrupt handling in ISR. I switched to semaphore to properly handle it. 

However I found another issue with high speed FSK: the code cannot keep up refilling FIFO with the TX data. If message is ~64bytes, then it can be sent in one go. Messages over 64 bytes are sent in several updates.

**Comment by dernasherbrezon** [comment]
Solved. The issue was with FreeRTOS tick period - which was too big. I added explicit task switch and now messages with move than 64 bytes can be sent without any issues.
